import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FitApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className="font-yekanBakhRegular antialiased  bg-zinc-900"
      >
        {children}
      </body>
    </html>
  );
}
