import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/UserContext";

export const metadata: Metadata = {
  title: "FitApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className="font-yekanBakhRegular antialiased"
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
